platform :ios, '5'

xcodeproj 'Backdoor.xcodeproj'

pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'Facebook-iOS-SDK'
pod 'Base64'
pod 'HockeySDK'
pod 'UIImage-Categories'
pod 'SDWebImage'
pod 'CKRefreshControl'
pod 'google-plus-ios-sdk'
pod 'FlurrySDK'
pod 'NoticeView'

post_install do |installer|
  installer.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) _AFNETWORKING_ALLOW_INVALID_SSL_CERTIFICATES_=1'
    end
  end
end
